title: "Kavya Agrawal"
description: "Ph.D. Scholar | Groundwater Contamination | Remote Sensing | GIS | AI/ML/DL"
url: "https://KavyaAgrawal24.github.io"
baseurl: ""
author:
  name: "Kavya Agrawal"
  affiliation: "TERI School of Advanced Studies"
  email: "kavya.agrawal@terisas.ac.in"
markdown: kramdown
permalink: /research-notes/:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
